#include <stddef.h>
 extern unsigned char* builtin__assert_colony; extern unsigned int builtin__assert_colony_len;
extern unsigned char* builtin__buffer_colony; extern unsigned int builtin__buffer_colony_len;
extern unsigned char* builtin__crypto_colony; extern unsigned int builtin__crypto_colony_len;
extern unsigned char* builtin__dgram_colony; extern unsigned int builtin__dgram_colony_len;
extern unsigned char* builtin__events_colony; extern unsigned int builtin__events_colony_len;
extern unsigned char* builtin__fs_colony; extern unsigned int builtin__fs_colony_len;
extern unsigned char* builtin__http_colony; extern unsigned int builtin__http_colony_len;
extern unsigned char* builtin__net_colony; extern unsigned int builtin__net_colony_len;
extern unsigned char* builtin__os_colony; extern unsigned int builtin__os_colony_len;
extern unsigned char* builtin__path_colony; extern unsigned int builtin__path_colony_len;
extern unsigned char* builtin__punycode_colony; extern unsigned int builtin__punycode_colony_len;
extern unsigned char* builtin__querystring_colony; extern unsigned int builtin__querystring_colony_len;
extern unsigned char* builtin__stream_colony; extern unsigned int builtin__stream_colony_len;
extern unsigned char* builtin__string_decoder_colony; extern unsigned int builtin__string_decoder_colony_len;
extern unsigned char* builtin__tty_colony; extern unsigned int builtin__tty_colony_len;
extern unsigned char* builtin__url_colony; extern unsigned int builtin__url_colony_len;
extern unsigned char* builtin__util_colony; extern unsigned int builtin__util_colony_len;
extern unsigned char* builtin__zlib_colony; extern unsigned int builtin__zlib_colony_len;
const dir_reg_t dir_index_builtin[] = { {"~assert.colony", (unsigned char*) &builtin__assert_colony, builtin__assert_colony_len}, {"~buffer.colony", (unsigned char*) &builtin__buffer_colony, builtin__buffer_colony_len}, {"~crypto.colony", (unsigned char*) &builtin__crypto_colony, builtin__crypto_colony_len}, {"~dgram.colony", (unsigned char*) &builtin__dgram_colony, builtin__dgram_colony_len}, {"~events.colony", (unsigned char*) &builtin__events_colony, builtin__events_colony_len}, {"~fs.colony", (unsigned char*) &builtin__fs_colony, builtin__fs_colony_len}, {"~http.colony", (unsigned char*) &builtin__http_colony, builtin__http_colony_len}, {"~net.colony", (unsigned char*) &builtin__net_colony, builtin__net_colony_len}, {"~os.colony", (unsigned char*) &builtin__os_colony, builtin__os_colony_len}, {"~path.colony", (unsigned char*) &builtin__path_colony, builtin__path_colony_len}, {"~punycode.colony", (unsigned char*) &builtin__punycode_colony, builtin__punycode_colony_len}, {"~querystring.colony", (unsigned char*) &builtin__querystring_colony, builtin__querystring_colony_len}, {"~stream.colony", (unsigned char*) &builtin__stream_colony, builtin__stream_colony_len}, {"~string_decoder.colony", (unsigned char*) &builtin__string_decoder_colony, builtin__string_decoder_colony_len}, {"~tty.colony", (unsigned char*) &builtin__tty_colony, builtin__tty_colony_len}, {"~url.colony", (unsigned char*) &builtin__url_colony, builtin__url_colony_len}, {"~util.colony", (unsigned char*) &builtin__util_colony, builtin__util_colony_len}, {"~zlib.colony", (unsigned char*) &builtin__zlib_colony, builtin__zlib_colony_len}, { 0, 0, 0} };
