#!/usr/bin/env node

var colony = require('colony');

var bufs = [];
process.stdin.on('data', function (d) {
  bufs.push(d);
}).on('end', function () {
  var str = Buffer.concat(bufs).toString('utf-8');
  
  process.stdout.write(colony.colonize(str));
})